#!/usr/bin/env bash

__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $__dir/config.sh


get_help() {
    command="whatnext"
    echo "A tool to help schedule studies

    Usage:

    $command (edit-subjects|es)                                         opens the subjects on your editor
    $command (edit-subject-description|esd)                                 edit the subject description
    $command (edit-history|eh)                                             opens the history on your editor
    $command (done | -d ) <subject> <what was done> [what to do next]       opens the history on your editor
    $command total                                                          show how much did you spent in any activity
    $command log                                                            shows the log
    $command goal             show your goals status
    $command (edit-goals|eg)                                                edit your goals
    "
}

[[ "$@" =~ "--help" ]] || [[ "$*" =~ "-h" ]] || [[ "$*" =~ ^h$ ]] && {
    get_help
    exit
}

[[ "$1"  == "-d" ]] || [[ "$1"  == "done" ]]  && {
    $__dir/done.sh "${@:2}"
    exit
}

[[ "$1"  == "level" ]]  && {
    $__dir/level.sh "${@:2}"
    exit
}

[[ "$@"  =~ "total" ]] && {
    $__dir/timePerSubject.py "${@:2}" | less
    exit
}
[[ "$@"  =~ goal$ ]] && {
    $__dir/goals.sh "${@:2}"
    exit
}

[[ "$@"  == "summary" ]] && {
    echo "Done Today: "$($__dir/gateway.sh done_today | wc -l)
    echo "Done Week: "$($__dir/gateway.sh done_week | wc -l)
    exit
}

[[ "$@"  == "init" ]] && {
    $__dir/init.sh "${@:2}"
    exit
}

[[ "$@"  == "log" ]] && {
    $__dir/log.sh "${@:2}" | less
    exit
}

[[ "$@"  == "list-subjects" ]] && {
    $__dir/gateway.sh list_subjects_names
    exit
}

[[ "$@"  == "edit-goals" ]] || [[ "$@"  =~ "eg" ]] && {
    $EDITOR "$WHATNEXT_GOALS"
    exit
}

[[ "$@"  == "edit-subjects" ]] || [[ "$@"  == "es" ]] && {
    $EDITOR "$WHATNEXT_CONF"
    exit
}

[[ "$@"  =~ "edit-subject-description" ]] || [[ "$@"  =~ "esd" ]] && {
    subject=$2
    [[ ! $($__dir/gateway.sh listSubjectsNames | grep "$subject") ]]  && {
        echo 'subject not found'
        exit 1
    }
    file=$(echo /tmp/$(date "+%Y-%m-%d_%H-%I-%S"))
    subjectDescription=$($__dir/gateway.sh listSubjects | grep "$subject" | rev | cut -d'|' -f1 | rev )
    echo "$subjectDescription" | tr '_' '\n' > $file

    $EDITOR "$file"
    newContent=$(cat $file | tr '\n' '_')
    $__dir/gateway.sh addWhatToDoNextToSubjet "$subject" "$newContent"
    exit
}

[[ "$@"  == "eh" ]] || [[ "$@"  == "edit-history" ]] && {
    $EDITOR "$WHATNEXT_HISTORY"
    exit
}

[[ ! -z "$@" ]]  && {
    echo "Option not found"
    exit 1
}

$__dir/scheduler.py | less
