#!/usr/bin/env bash

__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"


[[ -z ${WHATNEXT_CONF+x} ]] && {
    WHATNEXT_CONF=~/.whatnext.conf
}

[[ -z ${WHATNEXT_HISTORY+x} ]] && {
    WHATNEXT_HISTORY=~/.whatnext_history
}


get_help() {
    echo "A tool to help schedule studies
    It considers a study period one hour and you cannot study in a row.

    Usage:

    $0 (edit-subjects|-es|-e)                                            opens the subjects on your editor
    $0 edit-history                                                   opens the history on your editor
    $0 (done | -d ) <subject> <what was done> [what to do next]       opens the history on your editor
    $0 summary                                                        displays statistics about your usage
    $0 log                                                            shows the log
    "
}

[[ "$@" =~ "--help" ]] || [[ "$@" =~ ^-h$ ]]&& {
    get_help
    exit
}

[[ "$1"  == "-d" ]] || [[ "$1"  == "done" ]]  && {
    $__dir/done.sh "$@"
    exit
}

[[ "$@"  == "summary" ]] && {
    echo "Done Today: "$($__dir/gateway.sh done_today | wc -l)
    echo "Done Week: "$($__dir/gateway.sh done_week | wc -l)
    exit
}

[[ "$@"  == "init" ]] && {
    [ ! -f "$WHATNEXT_CONF" ] && {
       echo "myFirstSubject|50|50|do something" > "$WHATNEXT_CONF"
    }

    [ ! -f "$WHATNEXT_HISTORY" ] && {
       echo "myFirstSubject|50|50|do something" > "$WHATNEXT_HISTORY"
    }
    exit
}



[[ "$@"  == "log" ]] && {
    log_data() {
    log=$(tac "$WHATNEXT_HISTORY")
    current_entry=$(echo "$log" | wc -l )
IFS='
'
    for i in $log
    do
        date=$(echo $i | cut -d '|' -f1)
        subject=$(echo $i | cut -d '|' -f2)
        description=$(echo $i | cut -d '|' -f3)
        echo -e "\e[5;33;40m $current_entry $subject \e[0m"
        echo "Date:     $date"
        echo "      $description"

        echo ""
        current_entry=$(( $current_entry - 1 ))

    done
}

    log_data | less
    exit
}



[[ "$@"  == "list-subjects" ]] && {
    $__dir/gateway.sh list_subjects_names
    exit
}

[[ "$@"  == "edit-subjects" ]] || [[ "$@"  == "-es" ]] || [[ "$@"  == "-e" ]] && {
    [ ! -z ${EDITOR+x} ] && {
        $EDITOR "$WHATNEXT_CONF"
    } || {
        vim "$WHATNEXT_CONF"
    }
    exit
}

[[ "$@"  == "edit-history" ]] && {
    [ ! -z ${EDITOR+x} ] && {
        $EDITOR "$WHATNEXT_HISTORY"
    } || {
        vim "$WHATNEXT_HISTORY"
    }
    exit
}

$__dir/scheduler.py | less
