#!/usr/bin/env bash

__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $__dir/config.sh


get_help() {
    command="whatnext"
    echo "A tool to help schedule studies 
    Usage:

    $command (done | -d ) <subject> <what was done> [what to do next]       opens the history on your editor
    $command total                                                          show how much did you spent in any activity
    $command log                                                            shows the log
    $command (status|s)                                                     get current status of your studies
    $command goal                                                           show your goals status
    $command (edit-goals|eg)                                                edit your goals
    $command (edit-subjects|es)                                             opens the subjects on your editor
    $command (add) <subject> <importance> <complexity>                      adds a new subject
    $command (add) <subject>                                                remove a subject
    $command (edit-subject-description|esd)                                 edit the subject description
    $command (edit-history|eh)                                              opens the history on your editor
    "
}

[[ "$*" =~ ^--help$ ]] || [[ "$*" =~ ^-h$ ]] || [[ "$*" =~ ^h$ ]] && {
    get_help
    exit
}

[[ "$1"  == "-d" ]] || [[ "$1"  == "done" ]]  && {
    shift
    $__dir/done.sh "$@"
    exit
}

[[ "$1"  == "level" ]]  && {
    shift
    $__dir/level.sh "$@"
    exit
}

[[ "$1"  =~ "detail" ]]  && {
    shift
    $__dir/detail.py "$@" | less
    exit
}

[[ "$1"  = "add" ]]  && {
    shift
    $__dir/add.sh "$@" | less
    exit
}

[[ "$1"  = "rm" ]]  && {
    shift
    $__dir/rm.sh "$@" | less
    exit
}


[[ "$*"  =~ "total" ]] && {
    shift
    $__dir/timePerSubject.py human "$@" | less
    exit
}
[[ "$*"  =~ goal$ ]] && {
    shift
    $__dir/goals.sh "$@"
    exit
}

[[ "$*"  == "status" ]] || [[ "$*"  == "s" ]] && {
    shift
    $__dir/status.sh "$@"

    echo ""
    echo -e "$sectionColor""Goals$resetColor"
    $__dir/goals.sh | head -n 5

    echo ""
    echo -e "$sectionColor""Top subjects$resetColor"


    result=$($__dir/timePerSubject.py human)
    echo "$result" | tail -n1
    echo "$result" | head -n 5

    exit
}

[[ "$*"  == "init" ]] && {
    shift
    $__dir/init.sh "$@"
    exit
}

[[ "$*"  =~ "log" ]] && {
    shift
    $__dir/log.sh "$@" | less
    exit
}

[[ "$*"  == "list-subjects" ]] && {
    $__dir/gateway.sh list_subjects_names
    exit
}

[[ "$*"  == "edit-goals" ]] || [[ "$*"  =~ ^eg$ ]] && {
    $EDITOR "$WHATNEXT_GOALS"
    exit
}

[[ "$*"  == "edit-subjects" ]] || [[ "$1"  == "es" ]] && {
    $EDITOR "$WHATNEXT_CONF"
    exit
}

[[ "$*"  =~ "edit-subject-description" ]] || [[ "$*"  =~ "esd" ]] && {
    shift
    $__dir/editSubjectDescription.sh "$@"
    exit
}

[[ "$*"  == "eh" ]] || [[ "$*"  == "edit-history" ]] && {
    $EDITOR "$WHATNEXT_HISTORY"
    exit
}

[[ ! -z "$*" ]]  && {
    echo "Option not found"
    exit 1
}

if [ ! -z ${NO_COLOR+x} ]
then
    $__dir/scheduler.py
else
    $__dir/scheduler.py | less
fi

